name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pandas openpyxl pillow

      - name: Build EXE
        run: |
          pyinstaller --onefile --clean --name bimsa_etl --add-data "logo_bimsa.jpg;." --collect-all pandas --collect-all openpyxl --collect-all PIL Bimsa_Cli.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: bimsa-cli
          path: dist/Bimsa_etl.exe